### ISSUE TITLE
Bump version of swc_core to 0.101.4

### ISSUE THREAD

**Issue by ardeois** [lingui/swc-plugin#110]
I'm quite new to using this plugin but I've tried to use latest rspack tool and use swc loader with this lingui plugin

However, the `swc_core` is not compatible with `rspack@1.0.0-rc.1`
They currently use version 0.101.4 https://github.com/web-infra-dev/rspack/blob/main/Cargo.toml#L76

Would it be possible to bump the package with latest swc_core?

**Comment by dominikdosoudil** [comment]
I've just opened PR https://github.com/lingui/swc-plugin/pull/111

**Comment by dominikdosoudil** [comment]
Solved in #111, released in 4.0.10

**Comment by andrii-bodnar** [comment]
@dominikdosoudil could you please also update the compatibility table in the Readme?

**Comment by dominikdosoudil** [comment]
@andrii-bodnar yep, I got it on my to-do list

**Comment by dominikdosoudil** [comment]
> @andrii-bodnar yep, I got it on my to-do list

#115

**Comment by sondr3** [comment]
Would it be possible to get this changes into the `next` branch too? The list of unmet peer dependencies keep growing by the day 😅
