### ISSUE TITLE
Panicked error when building on AWS

### ISSUE THREAD

**Issue by Liviaparaujo** [lingui/swc-plugin#116]
Had the dependency set as ^4.0.8, had to change it to 4.0.8, it went smootly

<details><summary>Code Build Output</summary>
<p>

<html>
<body>

thread 'thread 'thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs<unnamed>:266:' panicked at 67:
--
115 | /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rscalled `Result::unwrap()` on an `Err` value: LayoutError
116 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
117 | :<unnamed>266' panicked at :/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs67:266:
118 | :called `Result::unwrap()` on an `Err` value: LayoutError67
119 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
120 | :
121 | called `Result::unwrap()` on an `Err` value: LayoutError
122 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
123 | thread 'thread 'nodenode' panicked at ' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs::166166::1414:
124 | :
125 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/404.tsx")'
126 |  
127 | Caused by:
128 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
129 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
130 | 2: RuntimeError: unreachable
131 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
132 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
133 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
134 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
135 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
136 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
137 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
138 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
139 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
140 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
141 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
142 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
143 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
144 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/_error.tsx")'
145 |  
146 | Caused by:
147 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
148 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
149 | 2: RuntimeError: out of bounds memory access
150 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x388ad)
151 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
152 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
153 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
154 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
155 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
156 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
157 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
158 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
159 |  
160 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
161 | thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
162 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/_document.tsx")'
163 |  
164 | Caused by:
165 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
166 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
167 | 2: RuntimeError: unreachable
168 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
169 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
170 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
171 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
172 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
173 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
174 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
175 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
176 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
177 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
178 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
179 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
180 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
181 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
182 | thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
183 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/_app.tsx")'
184 |  
185 | Caused by:
186 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
187 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
188 | 2: RuntimeError: unreachable
189 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
190 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
191 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
192 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
193 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
194 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
195 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
196 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
197 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
198 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
199 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
200 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
201 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
202 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
203 | thread 'thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs:266:67<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs:266:67:
204 | called `Result::unwrap()` on an `Err` value: LayoutError
205 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
206 | :
207 | called `Result::unwrap()` on an `Err` value: LayoutError
208 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
209 | thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
210 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/activities.tsx")'
211 |  
212 | Caused by:
213 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
214 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
215 | 2: RuntimeError: unreachable
216 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
217 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
218 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
219 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
220 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
221 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
222 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
223 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
224 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
225 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
226 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
227 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
228 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
229 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
230 | thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs:266:67:
231 | thread 'thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
232 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/dataAnalysis.tsx")'
233 |  
234 | Caused by:
235 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
236 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
237 | 2: RuntimeError: unreachable
238 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
239 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
240 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
241 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
242 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
243 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
244 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
245 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
246 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
247 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
248 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
249 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
250 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
251 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
252 | called `Result::unwrap()` on an `Err` value: LayoutError<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rs:266thread ':<unnamed>67' panicked at :
253 | /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/impls/core/mod.rscalled `Result::unwrap()` on an `Err` value: LayoutError:
254 | 266note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
255 | :67:
256 | called `Result::unwrap()` on an `Err` value: LayoutError
257 |  
258 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
259 | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
260 | thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
261 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/healthCheck.tsx")'
262 |  
263 | Caused by:
264 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
265 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
266 | 2: RuntimeError: unreachable
267 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
268 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
269 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
270 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
271 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
272 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
273 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
274 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
275 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
276 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
277 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
278 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
279 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
280 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
281 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
282 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
283 | thread '<unnamed>' panicked at thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
284 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/calendar.tsx")'
285 |  
286 | Caused by:
287 | 0: failed to invoke `/codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /codebuild/output/src3062921010/src/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
288 | 1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
289 | 2: RuntimeError: unreachable
290 | at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
291 | at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
292 | at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
293 | at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
294 | at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
295 | at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
296 | at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
297 | at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
298 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
299 | at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
300 | at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
301 | at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
302 | at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
303 | at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
304 | thread 'node' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.24/src/plugin.rs:166:14:
305 | failed to invoke plugin: failed to invoke plugin on 'Some("/codebuild/output/src3062921010/src/src/pages/dataAnalysis2.tsx")'
306 |  

</body>
</html>

Had to crop part of the output because of size

</p>
</details>

**Comment by timofei-iatsenko** [comment]
Incompatible version of the plugin and swc-core 

https://github.com/lingui/swc-plugin?tab=readme-ov-file#compatibility
