### ISSUE TITLE
Remove the example from this repository

### ISSUE THREAD

**Issue by andrii-bodnar** [lingui/swc-plugin#121]
It seems that we already have two examples in the main repository:

- [React with Vite and SWC](https://github.com/lingui/js-lingui/tree/main/examples/vite-project-react-swc)
- [Next.js with SWC](https://github.com/lingui/js-lingui/tree/main/examples/nextjs-swc)

We also have [examples/nextjs](https://github.com/lingui/swc-plugin/tree/main/examples/nextjs) within the current repo. It feels like it's too many examples, and the example from that repo could be removed in favor of the two examples mentioned above.

**Comment by timofei-iatsenko** [comment]
I use this example to test that fresh built plugin works, but that's ok, i can test it  on examples in the main repo instead.
