### ISSUE TITLE
panic with 5.0.0-next.3

### ISSUE THREAD

**Issue by francois-pasquier** [lingui/swc-plugin#123]
When loading a page after upgrading to 5.0.0-next.3, I am getting a lot of instances of the following error.

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("~/project/packages/app/layouts/Dialog.tsx")'

Caused by:
    0: failed to invoke `~/project/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at ~/project/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: Failed to deserialize program received from host', /Users/geist/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.264.56/src/plugin.rs:162:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("~/project/packages/app/features/home/HomeScreen.tsx")'

```

**Comment by timofei-iatsenko** [comment]
Please ensure that you use compatible version for your runtime https://github.com/lingui/swc-plugin?tab=readme-ov-file#compatibility

**Comment by francois-pasquier** [comment]
> Please ensure that you use compatible version for your runtime https://github.com/lingui/swc-plugin?tab=readme-ov-file#compatibility

I am. I bumped all @lingui/ packages to 5.0.0-next.3

**Comment by timofei-iatsenko** [comment]
Please read it one more time. You have incompatible version of your runtime (next / rspack / farm / swc-core / etc), not the other lingui packages.
