### ISSUE TITLE
Extract translation still requires @babel/preset-react

### ISSUE THREAD

**Issue by bafxyz** [lingui/swc-plugin#13]
Great plugin, one thing which doesn't work for me is 

NODE_ENV=development lingui extract --clean

This is the error
Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-jsx) to the 'plugins' section to enable parsing.

Do you know any workarounds for this one?

**Comment by thekip** [comment]
https://github.com/lingui/swc-plugin/blob/main/examples/nextjs-13/lingui.config.js

Look at the example, and read a Readme there is paragraph about that

**Comment by thekip** [comment]
https://github.com/lingui/swc-plugin/tree/main/examples/nextjs-13#important-notes

>- You should not have a babel config in the project, otherwise Next will turn off SWC compiler in favor of babel.
>- All babel dependencies used only for lingui extractor. The actual code is compiled with SWC + Lingui SWC plugin.

> Please can this be reopened as this somewhat defeats the purpose of using swc if babel still gets used for the extract pass?

SWC plugin used for transpiling your code while building/bundling. It unblocks using latest nextjs with it's default compiler with all benefits, or speeding your **build** by replacing babel to swc. 

Regarding extracting. Extractor is still written in Js and there no plans to write in Rust. The extraction itself is fast enough even whith babel, so there no just no sense in doing that. 

PS in version 4, which you can try right now you don't need to install babel dependencies to make extractor work.
