### ISSUE TITLE
<Trans> macro not working within `@vitejs/plugin-react-swc` in dev mode

### ISSUE THREAD

**Issue by mcintyret** [lingui/swc-plugin#131]
I'm having trouble getting vite + lingui + swc working together in dev mode

When running `vite dev`, the non-jsx macros get processed just fine, but `<Trans />` and `<Plural />` don't - the macro imports get removed, but don't get replaced with the react imports. The result is a ton of `Trans is undefined` errors at runtime.

My guess is that some processing of the jsx elements is happening before the `lingui/swc-plugin` executes, meaning that the conditions looking for the `<Trans />` jsx element don't hit.

The issue looks very similar to https://github.com/lingui/swc-plugin/issues/74, except that that issue was using rollup and I'm using vite (which I believe doesn't use rollup at all in dev mode). I'm hoping there's a similarly simple config solution in my case, but I haven't been able to figure it out!

versions:
```json
"@lingui/react": "^4.14.0",
"@lingui/vite-plugin": "^4.13.0",
"@lingui/swc-plugin": "4.0.8",
"@vitejs/plugin-react-swc": "^3.7.2",
"vite": "^6.0.3",
```

vite config:
```js
import { defineConfig } from "vite";
import path from "path";
import { lingui } from "@lingui/vite-plugin";
import react from "@vitejs/plugin-react-swc";
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
  plugins: [
    react({
      tsDecorators: true,
      plugins: [["@lingui/swc-plugin", {}]],
    }),
    lingui(),
    nodePolyfills({
      include: ["stream"],
      globals: {
        global: true,
        process: true,
      },
    }),
  ],
});
```

Thanks, and let me know if any more info would be helpful!

**Comment by timofei-iatsenko** [comment]
Unfortunately, i could not help without a reproduction here.

**Comment by mcintyret** [comment]
Turns out it was because of the `nodePolyfills` plugin. I don't know why but it seems to be outputting transformed jsx.

The solution was to wrap the react plugin with `enforce: "pre"` to make sure it executes before `nodePolyfills`.

Good to close!
