### ISSUE TITLE
Whitespaces & Trimming

### ISSUE THREAD

**Issue by thekip** [lingui/swc-plugin#2]
Original Babel Macro use following code: 

```js
// replace whitespace before/after newline with single space
const keepSpaceRe = /\s*(?:\r\n|\r|\n)+\s*/g
// remove whitespace before/after tag or expression
const stripAroundTagsRe = /(?:([>}])(?:\r\n|\r|\n)+\s*|(?:\r\n|\r|\n)+\s*(?=[<{]))/g

function normalizeWhitespace(text) {
  return (
    text
      .replace(stripAroundTagsRe, "$1")
      .replace(keepSpaceRe, " ")
      // keep escaped newlines
      .replace(/\\n/g, "\n")
      .replace(/\\s/g, " ")
      // we remove trailing whitespace inside Plural
      .replace(/(\s+})/gm, "}")
      .trim()
  )
}
```

And not only.  Also few pieces are spread among other code. There are few problems with this: 

I could not directly port this into Rust because Rust's Regexp engine doesn't support lookahead/lookbehind. 

So I need to write a code which should mimic this behavior in rust code. To do so i should understand all edge cases and generic spec behind this part of code.

This is so crucial because if even one additional space character in the processed after macro code it will cause translation mismatch (no translation for string would be found)

The only one source of truth for now is babel/macro fixtures, but i'm afraid they might not cover all cases which this regexp include.

So if someone has an idea and would like to help me with that i would appreciate this.

**Comment by renchap** [comment]
Would https://docs.rs/fancy-regex/latest/fancy_regex/ be a solution? It supports more features, with a reduced security, but as this is parsing the developer's code and only ran on build, it should be okay?

**Comment by thekip** [comment]
Thanks for the lib. For the current stage i've found more or less working regexp counterpart without lookahead/lookbehind. 
The main test is passing. The bigger issue it that in js macro there no enough tests with all cases to check all edge cases. So i think it's going to be a painful process of try and error on the real projects.

**Comment by zvictor** [comment]
This is an interesting thread.

I have been having problems with translations that contain newlines but I haven't managed to build a simple reproducible of that. It's just so weird...

I tried adding my use case as part of the tests of this repo, but there it works even though in my big project it fails whenever I add newlines to my texts. 🥲

**Comment by thekip** [comment]
@zvictor how exactly it fails?
