### ISSUE TITLE
4.0.0-next.2 Could not resolve dependency

### ISSUE THREAD

**Issue by sultan99** [lingui/swc-plugin#44]
It fails to install the next version 4.0.0-next.2

I guess it can be fixed by setting peer dependency to `>= 4.0.0-next < 5`.
```json
"peerDependencies": {
  "@lingui/macro": ">= 4.0.0-next < 5"
}
```
<img width="659" alt="image" src="https://user-images.githubusercontent.com/2598056/227368709-877f9832-4158-44f6-8953-422d4521234e.png">

**Comment by thekip** [comment]
Just ignore it for now. It wouldn't be an issue when v4 would finally released.
