### ISSUE TITLE
Pluging won't work anymore with next 13.3.1 (tested with up to canary 17)

### ISSUE THREAD

**Issue by shouze** [lingui/swc-plugin#51]
Maybe related to #39

I've opened a similar issue yesterday for https://github.com/blitz-js/next-superjson-plugin/issues/76 that has been fixed by https://github.com/blitz-js/next-superjson-plugin/pull/77

**Comment by thekip** [comment]
Yes, it's duplicate of https://github.com/lingui/swc-plugin/issues/39
