### ISSUE TITLE
Please update the Lingui 4.0 example code

### ISSUE THREAD

**Issue by usercao** [lingui/swc-plugin#55]
Currently, there are only sample projects for [vite-project-react-babel](https://github.com/lingui/js-lingui/tree/next/examples/vite-project-react-babel) in `js-lingui`, can you update the examples using `swc-plugin`? Because I want to know how `.swcrc` is included in `vite.config.ts` instead of adding `.swcrc`. Thanks.

**Comment by andrii-bodnar** [comment]
Hi @usercao,

please check these examples - https://github.com/lingui/js-lingui/tree/next/examples

**Comment by usercao** [comment]
Hi @andrii-bodnar ,
May I ask if the writing in `next.config.js` and `vite.config.js` is consistent with the example code [nextjs-swc](https://github.com/lingui/js-lingui/tree/next/examples/nextjs-swc)?
```javascript
swcPlugins: [
  ['@lingui/swc-plugin', {}],
]

plugins: ['@lingui/swc-plugin'],
```
Because as far as I know, their construction methods are not the same. Is adding a `vite-project-react-swc` more user-friendly?
