### ISSUE TITLE
Issue with variable naming convention for Lingui strings

### ISSUE THREAD

**Issue by behnamazimi** [lingui/swc-plugin#58]
**Issue: Error: failed to process called Result::unwrap() on an Err value: DummyBytePos**

**Description:**
When using Lingui strings with the "t" method, an error occurs when the variable names for these strings start with a capital letter and are placed outside of any code block, such as the file body scope. This error message is displayed:

```
Error: failed to process called `Result::unwrap()` on an `Err` value: DummyBytePos
```

Here is an example of the code structure that causes the error:

```javascript
import { t } from "@lingui/macro";

const MSG = t`message`;
```

And examples where the code works without any issues:
```javascript
import { t } from "@lingui/macro";

{
  const MSG = t`message`;
}

const text = t`text`;

const getMSG = () => { 
  const MY_MSG = t`message`;
  return MY_MSG;
}
```

**Dependencies:**
```
"@lingui/core": "^4.0.0",
"@lingui/macro": "^4.0.0",
"@lingui/react": "^4.0.0",
"@lingui/swc-plugin": "^4.0.0",
```

**Update:**
I'm also using NextJs 13.3.2

**Comment by behnamazimi** [comment]
I am using NextJs 13.3.2 without any other SWC plugins. @thekip

**Comment by thekip** [comment]
Please create a minimal reproducible example.

**Comment by root-io** [comment]
Same issue, everything was working fine until I updated my dependencies (+ reset lock) to lingui to 4.1.2 and next to 13.4.2:

After running `npm run build`:

```shell
- info Creating an optimized production build ...thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.41/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/foo/src/pages/_app.tsx")'

Caused by:
    0: failed to invoke `/foo/node_modules/.pnpm/@lingui+swc-plugin@4.0.0_@lingui+macro@4.1.2/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /foo/node_modules/.pnpm/@lingui+swc-plugin@4.0.0_@lingui+macro@4.1.2/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.5/src/plugin.rs:221:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.41/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/foo/src/pages/mypage.tsx")'
```

**Comment by thekip** [comment]
@root-io please read [Compatibility Section](https://github.com/lingui/swc-plugin#compatibility) of the readme. It seems nextjs 13.4.2 uses newer version of the swc-core wich is not yet compatible with this plugin https://swc.rs/docs/plugin/selecting-swc-core#v0760

**Comment by root-io** [comment]
Ah oups, I edited my last comment, nextjs 13.4.3 is not compatible, reverted back to 13.4.2, thanks it works!

**Comment by thekip** [comment]
@root-io we've deployed https://github.com/lingui/swc-plugin/releases/tag/4.0.1 which is built with `swc-core@0.76.0` and should support next@13.4.3 and above

@behnamazimi is your original issue is still relevant?

**Comment by behnamazimi** [comment]
Hey, still the same. here is the reproduction repo, please: 
https://github.com/behnamazimi/lingui-swc-plugin-issue-58

**Comment by thekip** [comment]
@behnamazimi thanks for the repro. It seems it's related to swc's react refresh transform bundled with nextjs. I will try to investigate what exactly go wrong.

**Comment by thekip** [comment]
@behnamazimi anyway using `t` outside of function in the module scope is not going to work. This is not particularly a solution, but might help to avoid the issue.

**Comment by thekip** [comment]
Issue got fixed in upstream https://github.com/swc-project/swc/issues/7471 

Closing this.
