### ISSUE TITLE
SWC 4.0.1 plugin panics on latest @swc/core version 1.3.60

### ISSUE THREAD

**Issue by chrischen** [lingui/swc-plugin#61]
**Describe the bug**
If I have @swc/core 1.3.60 I get a panic and server fails to start. Forcing 1.3.49 fixes the issue and it works. 1.3.56 seems to be the highest version that still works.

@lingui/swc-plugin 4.0.1 does not work with any version (I tried @swc/core 1.3.49 up to 1.3.60).
@lingui/swc-plugin 4.0.0 works with up to @swc/core 1.3.56.

**To Reproduce**
Install @swc/core 1.3.60 and run project with @lingui/swc-plugin.

Adding this to package.json and reinstalling fixes the issue, suggesting it is just the new swc version causing the problem.
```json
  "resolutions": {
    "@swc/core": "1.3.49"
  },
```

**Expected behavior**
It should not panic and crash.

**Additional context**

- jsLingui version 4.1.2
- Babel version 7.21.8
- Macro support:
 - [X ] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import linaria from "@linaria/vite";
import { lingui } from "@lingui/vite-plugin";

export default defineConfig({
  plugins: [
    react({
      plugins: [
        [
          "@lingui/swc-plugin", {}
        ],
      ],
    }),
    linaria(),
    lingui(),
  ],
});

```

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.41/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/[redacted]/src/entry/server.tsx")'

Caused by:
    0: failed to invoke `/Users/[redacted]/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/[redacted]/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.261.25/src/plugin.rs:152:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/[redacted]/src/entry/server.tsx")'

Caused by:
    0: failed to invoke `/Users/[redacted]/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/[redacted]/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable] {
  code: 'GenericFailure',
  plugin: 'vite:react-swc',

```

**Comment by thekip** [comment]
That is strange. `4.0.1` just built with latest available swc-core, which should support @swc/core@1.3.58 and up.  
I noticed swc project uses different version of rust compiler, may be this is an issue, will check that.

**Comment by stovmascript** [comment]
@thekip I tried building after updating `swc_core` to `0.76.18` and [using it](https://github.com/lingui/swc-plugin/blob/main/CONTRIBUTING.md#building-for-production) with [Next.js 13.4.4, which uses the same `swc_core` version](https://github.com/vercel/next.js/releases/tag/v13.4.4), but am also getting errors when running the dev server, albeit with similar output only sometimes.

I'm available on discord for cross checking or maybe some other work, if you need..

**Comment by stovmascript** [comment]
@thekip Tried building with [`nightly-2023-03-20`](https://github.com/swc-project/swc/blob/main/rust-toolchain) (hope that's the right way of changing the rust compiler version), but getting the same result.

**Comment by thekip** [comment]
It's getting annoying.  Did you try this with a bare swc/core? There might be something broken in nextjs as it was recently.

**Comment by stovmascript** [comment]
Yeah, I get ya... Not sure, I updated `swc_core` `version` in Cargo.toml and the rust-toolchain file and ran build and test. It seems to have updated stuff and did what I would expect, but I'm not ample with Rust yet, so might have missed something.

**Comment by bigint** [comment]
Yes happened the same here https://github.com/lensterxyz/lenster/pull/2975

**Comment by thekip** [comment]
4.0.2 version is now working with latest next-swc and bare `@swc/core`.
