### ISSUE TITLE
Next 13.4.3 onwards issue with swcPlugins

### ISSUE THREAD

**Issue by TimFL** [lingui/swc-plugin#62]
Hello,

as of Next 13.4.3 I'm having issues with this plugin being used in my project. I troubleshooted on a blank Next project and my current work project, with both projects having the same dependency setup.

The second I add this to my next.config:
`experimental: {
    swcPlugins: [
        [
	    "@lingui/swc-plugin",
	    {}
	]
    ]
}`
My project dies with the following error messages from that issue: https://github.com/vercel/next.js/issues/36078#issuecomment-1569624304

Could this, be in any way, related to the swc Plugin? I've trialed another swc plugin and it didn't cause the issue.

Running the 4.0.0 Plugin due to the swc core issue.

**Comment by thekip** [comment]
Tracking PR fixing thie issue: https://github.com/vercel/next.js/pull/50651

**Comment by lucasterra** [comment]
Tested with [`next@13.4.5-canary.7`](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.7) and [`@lingui/swc-plugin@v4.0.2`](https://github.com/lingui/swc-plugin/releases/tag/4.0.2) and it works for me.

**Comment by where-are-the-turtles** [comment]
hey @thekip! It doesn't seem to work with `4.2.1`: https://github.com/where-are-the-turtles/js-lingui/tree/main/examples/nextjs-swc.

**Comment by thekip** [comment]
@where-are-the-turtles  it's not enought information from your comment, what and how exactly not working.

**Comment by where-are-the-turtles** [comment]
> @where-are-the-turtles it's not enought information from your comment, what and how exactly not working.

there are a bunch of errors from the loader:

```
./node_modules/@lingui/loader/dist/index.cjs!./src/locales/pt.po
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "src/locales/en.po"
```

**Comment by thekip** [comment]
it's just a warning. Just ignore it for now, it's not related to SWC plugin and already a known issue.
