### ISSUE TITLE
Error on build: Filesystem cache is not enabled, cannot read plugin from phsyical path

### ISSUE THREAD

**Issue by behnamazimi** [lingui/swc-plugin#63]
Hi there,

I'm currently facing an error while trying to build my NextJS project with the latest version of dependencies. The error message is as follows:

> ./node_modules/next/dist/pages/_document.js
> Error: Filesystem cache is not enabled, cannot read plugin from physical path
> 
> ./node_modules/next/dist/pages/_error.js
> Error: Filesystem cache is not enabled, cannot read plugin from physical path
> 
> ./src/pages/[locale]/index.tsx
> Error: Filesystem cache is not enabled, cannot read plugin from physical path
> 
> ./src/pages/_app.tsx
> Error: Filesystem cache is not enabled, cannot read plugin from physical path
> 
> ./src/pages/index.tsx
> Error: Filesystem cache is not enabled, cannot read plugin from physical path

Here are the relevant dependencies:

```
"dependencies": {
  "@lingui/core": "^4.2.0",
  "@lingui/react": "^4.2.0",
  "next": "13.4.4",
  "react": "18.2.0",
  "react-dom": "18.2.0"
},
"devDependencies": {
  "@lingui/cli": "^4.2.0",
  "@lingui/loader": "^4.2.0",
  "@lingui/macro": "^4.2.0",
  "@lingui/swc-plugin": "^4.0.1",
  "@types/node": "20.1.5",
  "@types/react": "18.2.6",
  "eslint": "8.35.0",
  "eslint-config-next": "12.3.4",
  "typescript": "5.0.4"
}
```

To reproduce the issue, you can refer to [this example repository](https://github.com/behnamazimi/nextjs-swc-example).

Please note that the repository has two commits. The first commit represents a working setup with outdated dependencies, while the last commit is the one causing the error.

Any assistance or guidance in resolving this issue would be greatly appreciated.

Thank you!

**Comment by thekip** [comment]
There is anregression in upstream (next-swc) project:  here is PR fixing https://github.com/vercel/next.js/pull/50651

Related issues: https://github.com/swc-project/swc/issues/7470#issuecomment-1571585905 and https://github.com/vercel/next.js/issues/36078#issuecomment-1569624304
