### ISSUE TITLE
Capitalization issues

### ISSUE THREAD

**Issue by T9-Forever** [lingui/swc-plugin#68]
`
import { t } from '@lingui/macro'

const Name = t`edsonlin`
console.log(Name)
`

@swc/core: 1.3.58
@lingui/swc-plugin: 4.0.2

it does not work, it seems that there is an error in the data

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DummyBytePos', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_react-0.172.25/src/refresh/mod.rs:159:74

-----------

but, if i write like next line 

`
import { t } from '@lingui/macro'

const name = t`edsonlin`
console.log(Name)
`

it works! so i think it maybe treat capitalization as react,  do you have any resolution to solve it? plz help me

**Comment by T9-Forever** [comment]
```
import { t } from '@lingui/macro'

const Name = t`edsonlin`
console.log(Name)
```

Upper case variables not work!


````
import { t } from '@lingui/macro'

const name = t`edsonlin`
console.log(name)
```

but lowercase variables work!!!

**Comment by thekip** [comment]
Duplicate https://github.com/lingui/swc-plugin/issues/58
