### ISSUE TITLE
Nextjs 13.x not working with typewind plugin using SWC

### ISSUE THREAD

**Issue by pawanrana1992** [lingui/swc-plugin#69]
I am also trying to use  [Typewind](https://typewind.vercel.app/docs/examples/next) with tailwind config. but it is not working. It seems we can't use any custom plugin with nextjs 13.x.

Also If i am trying to use babel. then its working fine but not able to use most of the latest support from nextjs 13 like `fonts` giving error. it is asking SWC environment.

Nextjs team please help fix this or give me a workaround to move further. it is extremely required for us.

I also raise some query on [Typewind](https://github.com/Mokshit06/typewind/issues/50) but it is related to Nextjs 13.x

**Comment by thekip** [comment]
@pawanrana1992 please read [compatibility table](https://github.com/lingui/swc-plugin#compatibility) carefully. The plugins indeed work with nextjs 13.*. You need to choose the right version of both. SWC plugins is experimental feature, they DO BREAK backward compatibility in patch and minor releases, so you need to choose an exact version of nextjs

**Comment by pawanrana1992** [comment]
Thanks @thekip , let me check
