### ISSUE TITLE
Macros are not processed inside .js/.mjs files.

### ISSUE THREAD

**Issue by chrischen** [lingui/swc-plugin#77]
It seems like the non-react macros (React isn't allowed in .js/.mjs anyways) like "t" are not processed inside .js or .mjs files. They are processed only in .ts, .tsx, and .jsx files.

The babel macros plugin does process the macro even in .js and .mjs files. Not sure if this is an SWC limitation.

```
// somefile.js
import { t } from '@lingui/macro';
const text = t`hello`;
```
```
[plugin:vite:import-analysis] The macro you imported from "@lingui/macro" is being executed outside the context of compilation. 
This indicates that you don't have the "babel-plugin-macros" or "@lingui/swc-plugin" configured correctly. Please see the documentation for how to configure Vite with Lingui correctly: https://lingui.dev/tutorials/setup-vite
```
I am on SWC core 1.3.56.
Vite 5.0.3.

**Comment by chrischen** [comment]
I forked the lingui repo and modified the react-swc example:
https://github.com/chrischen/js-lingui/commit/88e8e1912cae4ce501dc7985af3fed03aefacc04

If I simply swap out `@vitejs/plugin-react-swc` with `@vitejs/plugin-react` (which uses Babel) then the lingui JS macro works with used from a vanilla `.js` file.

Are you saying the issue is probably in `@vitejs/plugin-react-swc` since with Vite I don't really configure the build pipeline apart from the plugin? If so I will open this issue in the vitejs repo.

**Comment by thekip** [comment]
> Are you saying the issue is probably in @vitejs/plugin-react-swc since with Vite I don't really configure the build pipeline apart from the plugin? 

Yes, it is. They might skip js/mjs files because they don't need transpilation by theirs opinion.

**Comment by chrischen** [comment]
Ok I will cose and re-open the issue with them and see if they are open to changing it. My understanding is that SWC can be used for Macros, and macros can be used with vanilla JS files.

**Comment by thekip** [comment]
tracking issue https://github.com/vitejs/vite-plugin-react-swc/issues/182
