### ISSUE TITLE
How to use it with macro support?

### ISSUE THREAD

**Issue by longprao** [lingui/swc-plugin#8]
I would like to use this as a drop in replacement for babel, but it seems it's not possible if using macro? Mainly these code break

```
import { t, Trans } from '@lingui/macro'

<Trans>...some text...</Trans>

t`...some text...`
```

Without babel I always got this error

```
./node_modules/@lingui/conf/index.js:22:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/@lingui/macro/index.js

```

And this error

```
TypeError: _lingui_macro__WEBPACK_IMPORTED_MODULE_3__.t is not a function
```

**Comment by daviddutch** [comment]
If you have these errors it means the plugin is not used.

**Comment by thekip** [comment]
Exactly. This plugin aimed to bring macro support for SWC. Check your configuration, probably something wrong there.

**Comment by longprao** [comment]
Sorry but this took me hours, but I still can't get how to make that `Can't resolve 'fs'` error go away. 

I have removed `.babelrc` and all `babel` deps inside package.json.

I have tried adding `.swcrc` file with content:

```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "experimental": {
      "plugins": ["@lingui/swc-plugin", {
        
        // Optional
        // Unlike the JS version this option must be passed as object only.
        // Docs https://lingui.js.org/ref/conf.html#std-config-runtimeConfigModule
        "runtimeModules": {
          "i18n": ["@lingui/core", "i18n"],
          "trans": ["@lingui/react", "Trans"]
        }
      }]
    }
  }
}
```

And also tried adding this to `next.config.js`:

```
  compiler: {
    // see https://styled-components.com/docs/tooling#babel-plugin for more info on the options.
    styledComponents: true,
  },
  experimental: {
    swcPlugins: [
      [
        '@lingui/swc-plugin',
        {
          // Optional
          // Unlike the JS version this option must be passed as object only.
          // Docs https://lingui.js.org/ref/conf.html#std-config-runtimeConfigModule
          runtimeModules: {
            i18n: ['@lingui/core', 'i18n'],
            trans: ['@lingui/react', 'Trans'],
          },
        },
      ]
    ],
  },
  ```
  
  And various ways...
  
  Is there any more instructions to enable SWC with this plugin? 
  
  I notice there are still many babel packages installed inside node_modules, could that be the issue?

**Comment by thekip** [comment]
@longprao I created an example with nextjs 13 https://github.com/lingui/swc-plugin/pull/10

It's not ideal in terms of how lingui runtime modules are used, but at least macro expansion works with SWC plugin.
