### ISSUE TITLE
useLingui hook implementation

### ISSUE THREAD

**Issue by thekip** [lingui/swc-plugin#84]
https://github.com/lingui/js-lingui/pull/1859

**Comment by AndrewIngram** [comment]
Any way we can help get this over the line? (sadly I don't have any real Rust expertise)

**Comment by thekip** [comment]
I also didn't have any Rust expertise but learned specifically for that project. So it's not an excuse 🤪

Honestly i don't have enough motivation / time to continue working on that. Implementing this in Rust is much more complicated, since SWC and Rust ownership model doesn't give the same tools as babel do. So everything related to scopes, traversing, finding references, replacing references you should do on your own inside the Visitor's loop. You could not, for example, find a `useLingui` statement, get all bindings referencing this statement and transform them in a loop.

I think, it might be a good task for ChatGPT, we have input, we have output, and we simply need to write a transform.

**Comment by andrii-bodnar** [comment]
Available in [5.0.0-next.1](https://github.com/lingui/swc-plugin/releases/tag/5.0.0-next.1).
