### ISSUE TITLE
When parsing jsx, seems that it doesn't check that at least <Select /> tag is imported from lingui

### ISSUE THREAD

**Issue by shouze** [lingui/swc-plugin#9]
I've just tested the plugin on a project I own. First of all, thank you @thekip for your work, so easy to setup and works :zap:.

The only issue I've encountered from now is this one:
1. I have a `Select` component in the project
2. Seems that the plugin threat it as a lingui `<Select />` tag
3. So it results to the following error message: `Message cannot be parsed due to syntax errors: {0, select,}{1}`

In order to make it work and have a temporary fix, I've aliased our component (`import { Select as Selector } from ...`) so the plugin ignores it.

**Comment by thekip** [comment]
Thanks for the feedback. Glad to hear that it works besides this bug. 

it's true, plugin doesn't check origin of element.  In babel version babel-macro plugin was responsible for that. 
In SWC version I need to do this checks manually. I have it already in my list of tasks.

**Comment by thekip** [comment]
Fixed in https://github.com/lingui/swc-plugin/pull/11

These cases supported
```ts

import { Plural } from "@lingui/macro";
import { Select } from "./my-select-cmp";
;<Plural
 value={count}
 one="Message"
 other="Messages"
/>
;<Select prop="propValue">Should be untouched</Select>

// ↓ ↓ ↓ ↓ ↓ ↓

import { Trans } from "@lingui/react";
import { Select } from "./my-select-cmp";
;<Trans
    id={"{count, plural, one {Message} other {Messages}}"}
    values={{ count: count }}
 />
;<Select prop="propValue">Should be untouched</Select>
```

```ts
import { plural } from "@lingui/macro";
import { t } from "./custom-t";
 t`Don't touch me!`
 plural(value, {one: "...", other: "..."})

// ↓ ↓ ↓ ↓ ↓ ↓

import { i18n } from "@lingui/core";
import { t } from "./custom-t";
t`Don't touch me!`
i18n._("{value, plural, one {...} other {...}}", {
     value: value
 });

```

And even renamed imports supported (hope babel version also supports this, i haven't find such tests in theirs test-suite)

```ts
import { t as i18nT, plural as i18nPlural } from "@lingui/macro";
i18nT`Hello World!`;
i18nPlural(value, {one: "...", other: "..."});

// ↓ ↓ ↓ ↓ ↓ ↓

import { i18n } from "@lingui/core";
i18n._("Hello World!")
i18n._("{value, plural, one {...} other {...}}", {
     value: value
 });
```
